### ISSUE TITLE
命令行无法执行

### ISSUE THREAD

**Issue by xmncrx** [fastdlabs/fastD#128]
新拉的项目，不管是自定义的还是系统的命令行
比如php bin/server start 
都无法执行，访问就变成直接输出代码文件内容

虚拟机配置如下
php -v : 7.2
uname -a  : Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release : CentOS Linux release 7.6.1810 (Core)

**Comment by viliy** [comment]
先执行 ls  bin/  看输出内容，尝试执行 composer update -vvv

**Comment by xmncrx** [comment]
> 先执行 ls bin/ 看输出内容，尝试执行 composer update -vvv

还是不行。ls bin/就直接输出原有的那几个文件。composer update -vvv 之后reading一堆cache。最后返回generating autoload files 。然后我再次执行php bin/server start 依然没有变化。还是输出那些文件里面的内容。貌似没有识别

**Comment by viliy** [comment]
执行下： vendor/fastd/fastd/server status

**Comment by xmncrx** [comment]
> 执行下： vendor/fastd/fastd/server status

你应该是想执行vendor/fastd/fastd/bin/server status 吧。因为你发的这条命令说不存在，然后我执行了bin里面的server status 之后，还是报未找到命令

**Comment by viliy** [comment]
./vendor/fastd/fastd/server status

**Comment by xmncrx** [comment]
> ./vendor/fastd/fastd/server status

这条命令还是说没有那个文件或目录 我改成 ./vendor/fastd/fastd/bin/server status之后报错了。以下是报错信息
PHP Fatal error:  Uncaught ErrorException: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4. in /www/wwwroot/export.api.com/vendor/symfony/debug/Exception/FatalThrowableError.php:14
Stack trace:
#0 [internal function]: FastD\Application->FastD\{closure}(16384, 'The "Symfony\\Co...', '/www/wwwroot/ex...', 14, Array)
#1 /www/wwwroot/export.api.com/vendor/symfony/debug/Exception/FatalThrowableError.php(14): trigger_error('The "Symfony\\Co...', 16384)
#2 /www/wwwroot/export.api.com/vendor/composer/ClassLoader.php(444): include('/www/wwwroot/ex...')
#3 /www/wwwroot/export.api.com/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/ex...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 /www/wwwroot/export.api.com/vendor/fastd/fastd/src/Application.php(201): spl_autoload_call('Symfony\\Compone...')
#6 [internal function]: FastD\Application->handleException(Object(Error))
#7 {main}
  thrown in /www/wwwroot/export.api.com/vendor/symfony/debug/Exception/FatalThrowableError.php on line 14

Fatal error: Uncaught ErrorException: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4. in /www/wwwroot/export.api.com/vendor/symfony/debug/Exception/FatalThrowableError.php:14
Stack trace:
#0 [internal function]: FastD\Application->FastD\{closure}(16384, 'The "Symfony\\Co...', '/www/wwwroot/ex...', 14, Array)
#1 /www/wwwroot/export.api.com/vendor/symfony/debug/Exception/FatalThrowableError.php(14): trigger_error('The "Symfony\\Co...', 16384)
#2 /www/wwwroot/export.api.com/vendor/composer/ClassLoader.php(444): include('/www/wwwroot/ex...')
#3 /www/wwwroot/export.api.com/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/ex...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 /www/wwwroot/export.api.com/vendor/fastd/fastd/src/Application.php(201): spl_autoload_call('Symfony\\Compone...')
#6 [internal function]: FastD\Application->handleException(Object(Error))
#7 {main}
  thrown in /www/wwwroot/export.api.com/vendor/symfony/debug/Exception/FatalThrowableError.php on line 14

**Comment by viliy** [comment]
贴下代码目录结构和composer.json文件吧
